# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-2f49d536-ab5a-4fb0-bb6a-28ed2106bf6e";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-2f49d536-ab5a-4fb0-bb6a-28ed2106bf6e".device =
    "/dev/disk/by-uuid/2f49d536-ab5a-4fb0-bb6a-28ed2106bf6e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/54FF-AC7B";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-05fcdd55-5afe-4690-b195-ba0c86959954"; }
  ];

  boot.initrd.luks.devices."luks-05fcdd55-5afe-4690-b195-ba0c86959954".device =
    "/dev/disk/by-uuid/05fcdd55-5afe-4690-b195-ba0c86959954";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
