# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-a1d07fce-d536-4ff7-871f-11eb13fa25b4";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a1d07fce-d536-4ff7-871f-11eb13fa25b4".device =
    "/dev/disk/by-uuid/a1d07fce-d536-4ff7-871f-11eb13fa25b4";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5DB5-7D03";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f9925da7-40ca-4372-b4b0-3ab3f1c1d3c0"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
