name: Checkout
description: Checkout nix-config
runs:
  using: composite
  steps:
    - name: checkout
      shell: bash
      run: |
        if [ -d .git ]; then
          git fetch origin main
          git reset --hard origin/main
        else
          git clone https://github.com/zzzealed/nix-config .
        fi
