# Reversing default configs, so "q" saves position while "Q" doesn't.
q quit-watch-later
Q quit

# Copy filename or path
c run "/bin/sh" "-c" "echo -n \"${filename}\" | wl-copy" ; show-text "Copied filename"
C run "/bin/sh" "-c" "echo -n \"${path}\" | wl-copy" ; show-text "Copied path"
