# If enabled, `save-position-on-quit`
q quit
# Never `save-position-on-quit`
Q set save-position-on-quit no; quit

# Copy filename or path
c run "/bin/sh" "-c" "echo -n \"${filename}\" | wl-copy" ; show-text "Copied filename"
C run "/bin/sh" "-c" "echo -n \"${path}\" | wl-copy" ; show-text "Copied path"
