#no-config=yes

# Include
include="~~/profiles.conf"
include="~~/host.conf"
use-filedir-conf=no # I use "~~/scripts/dynamic-include.lua" now.

# General
autocreate-playlist=same
loop-file=yes
loop-playlist=no
idle=yes
keep-open=yes
drag-and-drop=append
geometry=50%x50%
cursor-autohide-fs-only=yes
load-auto-profiles=no
directory-mode=lazy
directory-filter-types=video,audio,image,archive,playlist
prefetch-playlist=no
cache=yes
save-position-on-quit=no # See `profiles.conf`
resume-playback=no
force-window=immediate

# OSC & OSD
osc=yes
osd-bar=no
osd-level=1
osd-on-seek=msg-bar
osd-playlist-entry=both
osd-font-size=20
osd-scale=1
osd-fractions=yes

# Seek
demuxer-max-back-bytes=250M
demuxer-max-bytes=500M

# Terminal
msg-color=yes
msg-module=yes
term-osd-bar=yes

# Video
video-sync=audio
#interpolation=yes
hls-bitrate=max
dither-depth=auto

# Audio
audio-file-auto=fuzzy
volume=50
volume-max=300
audio-pitch-correction=yes
audio-channels=auto-safe
alang=da,ja,en
audio-display=embedded-first

# Subtitles
sub-auto=all
sub-color=1.0/1.0/0.0/0.75
sub-outline-color=0.0/0.0/0.0/1.0
sub-outline-size=2
sub-back-color=0.0/0.0/0.0/1.0
sub-border-style=outline-and-shadow
sub-scale=1.0
sub-scale-with-window=yes
embeddedfonts=yes
sub-margin-y=155
slang=en,en.sdh,da,da.sdh
demuxer-mkv-subtitle-preroll=yes
sub-fix-timing=yes

# Screenshots
screenshot-format=png
screenshot-high-bit-depth = no
screenshot-tag-colorspace = no
screenshot-png-compression = 4
screenshot-directory = ~~desktop/

# YT-DL
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format=best
ytdl-raw-options=
