[watch-later]
ignore-path-in-watch-later-config=yes # We'll get back to this one
write-filename-in-watch-later-config=yes
watch-later-options=start,volume,sub,aid,vid,sub-delay,sub-speed,sub-pos,sub-visibility,sub-scale,sub-use-margins,sub-ass-force-margins,sub-ass-use-video-data,sub-ass-override,secondary-sid,secondary-sub-delay,secondary-sub-pos,secondary-sub-ass-override,secondary-sub-visibility
save-position-on-quit=yes
resume-playback=yes
chapters-file="chapters.txt"

[kino]
profile=watch-later # Include profile above
sub-auto=no
autocreate-playlist=no
directory-filter-types=video,playlist
osd-playlist-entry=title
