[watch-later] # I include this profile in `[movie]`, `[show]`, etc.
ignore-path-in-watch-later-config=yes # So "watch-later"-files stay cross platform
write-filename-in-watch-later-config=yes
watch-later-options=start,volume,sub,aid,vid,sub-delay,sub-speed,sub-pos,sub-visibility,sub-scale,sub-use-margins,sub-ass-force-margins,sub-ass-use-video-data,sub-ass-override,secondary-sid,secondary-sub-delay,secondary-sub-pos,secondary-sub-ass-override,secondary-sub-visibility
save-position-on-quit=yes
resume-playback=yes
chapters-file="chapters.txt"

[movie]
profile=watch-later
sub-auto=no
autocreate-playlist=no
directory-filter-types=video,playlist
osd-playlist-entry=title
loop-file=yes
loop-playlist=yes

[show]
profile=watch-later
sub-auto=no
autocreate-playlist=no
directory-filter-types=video,playlist
osd-playlist-entry=both
loop-file=no
loop-playlist=no

[audio]
autocreate-playlist=filter
directory-filter-types=audio,playlist
sub-margin-y=50
sub-scale=1.0
loop-file=no
loop-playlist=yes

[image]
save-position-on-quit=no
directory-filter-types=image
osc=no
loop-file=yes
loop-playlist=yes
load-scripts=no
