[Interface]
Address = 10.100.0.6/32
DNS = 10.100.0.1, 1.1.1.1, 1.0.0.1
ExcludedApplications = org.localsend.localsend_app
PrivateKey = <private-key>

[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = wg.zzzealed.com:51820
PublicKey = ShK/VV+el3nb6oGqpDIhJIVLgDQMucTASV6gGeIMwyw=
