# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."gpt4free" = {
    image = "hlohaus789/g4f:0.6.3.4";
    volumes = [
      "/var/lib/gpt4free/generated_images:/app/generated_images:rw"
      "/var/lib/gpt4free/har_and_cookies:/app/har_and_cookies:rw"
    ];
    ports = [
      "9090:8080/tcp"
      "7900:7900/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=gpt4free"
      "--network=gpt4free_default"
      "--shm-size=2147483648"
    ];
  };
  systemd.services."podman-gpt4free" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-gpt4free_default.service"
    ];
    requires = [
      "podman-network-gpt4free_default.service"
    ];
    partOf = [
      "podman-compose-gpt4free-root.target"
    ];
    wantedBy = [
      "podman-compose-gpt4free-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-gpt4free_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f gpt4free_default";
    };
    script = ''
      podman network inspect gpt4free_default || podman network create gpt4free_default
    '';
    partOf = [ "podman-compose-gpt4free-root.target" ];
    wantedBy = [ "podman-compose-gpt4free-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-gpt4free-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
