# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
#  networking.firewall.interfaces = let
#    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
#  in {
#    "${matchAll}".allowedUDPPorts = [ 53 ];
#  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."gpt4free" = {
    image = "hlohaus789/g4f:v6.7.3";
    volumes = [
      "/var/lib/gpt4free/generated_media:/app/generated_media:rw"
      "/var/lib/gpt4free/har_and_cookies:/app/har_and_cookies:rw"
    ];
    ports = [
      "9090:8080/tcp"
      "7900:7900/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=gpt4free"
      "--network=gpt4free_default"
      "--shm-size=2147483648"
    ];
  };
  systemd.services."podman-gpt4free" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-gpt4free_default.service"
    ];
    requires = [
      "podman-network-gpt4free_default.service"
    ];
    partOf = [
      "podman-compose-gpt4free-root.target"
    ];
    wantedBy = [
      "podman-compose-gpt4free-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-gpt4free_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f gpt4free_default";
    };
    script = ''
      podman network inspect gpt4free_default || podman network create --disable-dns gpt4free_default
    '';
    partOf = [ "podman-compose-gpt4free-root.target" ];
    wantedBy = [ "podman-compose-gpt4free-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-gpt4free-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
