theme = "base16_default" # Theme set through Stylix

[editor]
line-number = "relative"
bufferline = "multiple"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "read-only-indicator", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["spinner", "position"]

[editor.gutters]
layout = ["line-numbers", "spacer", "diff"]

# https://yazi-rs.github.io/docs/tips/#helix
[keys.normal]
C-y = [
	':sh rm -f /tmp/unique-ca1ea106',
	':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-ca1ea106',
	':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
	':open %sh{cat /tmp/unique-ca1ea106}',
	':redraw',
	':set mouse false',
  ':set mouse true',
]
