# https://writewithharper.com/docs/integrations/helix
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
userDictPath = ""
fileDictPath = ""
diagnosticSeverity = "warning"
isolateEnglish = false
dialect = "American"
maxFileLength = 120000

[language-server.harper-ls.config.harper-ls.linters]
SpellCheck = false
SpelledNumbers = false
AnA = true
SentenceCapitalization = false
UnclosedQuotes = true
WrongQuotes = false
LongSentences = true
RepeatedWords = true
Spaces = false
Matcher = true
CorrectNumberSuffix = true

[language-server.harper-ls.config.harper-ls.codeActions]
ForceStable = false

[language-server.harper-ls.config.harper-ls.markdown]
IgnoreLinkTitle = false

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]
