services:
  chrome:
    container_name: "chrome"
    image: ghcr.io/linuxserver/chrome:143.0.7499.169-1-ls62
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - "/var/lib/chrome:/config"
    shm_size: "2g"
    restart: unless-stopped
