# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
#  networking.firewall.interfaces = let
#    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
#  in {
#    "${matchAll}".allowedUDPPorts = [ 53 ];
#  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."chrome" = {
    image = "ghcr.io/linuxserver/chrome:143.0.7499.169-1-ls62";
    volumes = [
      "/var/lib/chrome:/config:rw"
    ];
    ports = [
      "3000:3000/tcp"
      "3001:3001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=chrome"
      "--network=chrome_default"
      "--shm-size=2147483648"
    ];
  };
  systemd.services."podman-chrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-chrome_default.service"
    ];
    requires = [
      "podman-network-chrome_default.service"
    ];
    partOf = [
      "podman-compose-chrome-root.target"
    ];
    wantedBy = [
      "podman-compose-chrome-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-chrome_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f chrome_default";
    };
    script = ''
      podman network inspect chrome_default || podman network create --disable-dns chrome_default
    '';
    partOf = [ "podman-compose-chrome-root.target" ];
    wantedBy = [ "podman-compose-chrome-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-chrome-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
