on:
  push:
    branches: [main]
    paths:
      - "flake.lock"
jobs:
  build-server:
    runs-on: [self-hosted, nix]
    steps:
      - uses: ./.github/actions/checkout
      - name: build server-nixos
        run: |
          nix build .#nixosConfigurations.server-nixos.config.system.build.toplevel \
            --log-format bar \
            --out-link /var/lib/github-runner/server-nixos/gcroots/server-nixos
  build-rest:
    needs: build-server
    strategy:
      matrix:
        host: [desktop-nixos, pi-nixos, vps-nixos]
      fail-fast: false
    runs-on: [self-hosted, nix]
    steps:
      - uses: ./.github/actions/checkout
      - name: build ${{ matrix.host }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel \
            --log-format bar \
            --out-link /var/lib/github-runner/server-nixos/gcroots/${{ matrix.host }}
  gatus-post:
    if: always()
    needs: [build-server, build-rest]
    runs-on: [self-hosted, nix]
    steps:
      - uses: ./.github/actions/report-status
        with:
          endpoint: github-com_actions-build-yml-workflow
          status: ${{ needs.build-server.result == 'success' && needs.build-rest.result == 'success' }}
          token: ${{ secrets.GATUS_GITHUB_TOKEN }}
