on:
  push:
    branches: [main]
    paths:
      - "flake.lock"
jobs:
  build-server:
    runs-on: [self-hosted, nix]
    timeout-minutes: 1440 # 24 hours
    steps:
      - uses: zzzealed/nix-config/.github/actions/checkout@main
      - name: build server-nixos
        run: |
          nix build .#nixosConfigurations.server-nixos.config.system.build.toplevel \
            --log-format bar \
            --out-link /var/lib/github-runner/server-nixos/gcroots/server-nixos
  build-hosts:
    needs: build-server
    timeout-minutes: 1440 # 24 hours
    strategy:
      matrix:
        host: [desktop-nixos, pi-nixos, vps-nixos, laptop-nixos]
      fail-fast: false
    runs-on: [self-hosted, nix]
    steps:
      - uses: zzzealed/nix-config/.github/actions/checkout@main
      - name: build ${{ matrix.host }}
        run: |
          nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel \
            --log-format bar-with-logs \
            --out-link /var/lib/github-runner/server-nixos/gcroots/${{ matrix.host }}

  build-phone:
    needs: build-server
    runs-on: [self-hosted, nix]
    timeout-minutes: 1440 # 24 hours
    steps:
      - uses: zzzealed/nix-config/.github/actions/checkout@main
      - name: build phone-droid
        run: |
          nix build .#legacyPackages.aarch64-linux.nix-on-droid-proot-static \
            --log-format bar-with-logs \
            --out-link /var/lib/github-runner/server-nixos/gcroots/nix-on-droid-proot-static
          nix build --impure .#nixOnDroidConfigurations.phone-droid.activationPackage \
            --log-format bar-with-logs \
            --out-link /var/lib/github-runner/server-nixos/gcroots/phone-droid

  gatus-post:
    if: always()
    needs: [build-server, build-hosts, build-phone]
    runs-on: [self-hosted, nix]
    steps:
      - uses: ./.github/actions/report-status
        with:
          endpoint: github-com_actions-build-yml-workflow
          status: ${{ needs.build-server.result == 'success' && needs.build-hosts.result == 'success' && needs.build-phone.result == 'success' }}
          token: ${{ secrets.GATUS_GITHUB_TOKEN }}
