on:
  workflow_run:
    workflows: ["eval"]
    branches: [main]
    types: [completed]
    paths:
      - "flake.lock"

jobs:
  cache:
    runs-on: [self-hosted, nix]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        run: |
          if [ -d .git ]; then
            git fetch origin main
            git reset --hard origin/main
          else
            git clone https://github.com/zzzealed/nix-config .
          fi

      - name: build desktop-nixos
        run: nix build .#nixosConfigurations.desktop-nixos.config.system.build.toplevel --out-link /var/lib/github-runner/server-nixos/gc-roots/desktop-nixos

      - name: build server-nixos
        run: nix build .#nixosConfigurations.server-nixos.config.system.build.toplevel --out-link /var/lib/github-runner/server-nixos/gc-roots/server-nixos

      - name: build pi-nixos
        run: nix build .#nixosConfigurations.pi-nixos.config.system.build.toplevel --out-link /var/lib/github-runner/server-nixos/gc-roots/pi-nixos

      - name: build vps-nixos
        run: nix build .#nixosConfigurations.vps-nixos.config.system.build.toplevel --out-link /var/lib/github-runner/server-nixos/gc-roots/vps-nixos
