on:
  push:
    branches: [main]
    paths-ignore:
      - "flake.lock"
jobs:
  check-no-build:
    runs-on: [self-hosted, nix]
    steps:
      - uses: ./.github/actions/checkout
      - name: check outputs without building
        run: |
          nix flake check --no-build \
            --all-systems \
            --log-format bar
  gatus-post:
    if: always()
    needs: [check-no-build]
    runs-on: [self-hosted, nix]
    steps:
      - uses: ./.github/actions/report-status
        with:
          endpoint: github-com_actions-check-no-build-yml-workflow
          status: ${{ needs.check-no-build.result == 'success' }}
          token: ${{ secrets.GATUS_GITHUB_TOKEN }}
