on:
  push:
    branches: [main]
    paths:
    - "flake.lock"

jobs:
  check:
    runs-on: [self-hosted, nix]
    steps:
      - name: checkout
        run: |
          if [ -d .git ]; then
            git fetch origin main
            git reset --hard origin/main
          else
            git clone https://github.com/zzzealed/nix-config .
          fi

      - name: check outputs
        run: nix flake check --verbose

      - name: report status
        if: always() # Run even on fail
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            STATUS=true
          else
            STATUS=false
          fi
          curl -f -X POST \
            -H "Authorization: Bearer ${{ secrets.GATUS_GITHUB_TOKEN }}" \
            "https://status.rotte.city/api/v1/endpoints/github-com_actions-check-yml-workflow/external?success=$STATUS"
